services:
  postgres:
    image: postgres:latest
    mem_limit: 512m
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=db_items
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -u postgres"]
      interval: 5s
      timeout: 2s
      retries: 60
  dashboard:
    image: dashboard-items:latest
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      - DB_USERNAME=user
      - DB_PASSWORD=password
      - JDBC_URL=jdbc:postgresql://host.docker.internal:5432/db_items
    depends_on:
      postgres:
        condition: service_started